---
controller_hosts:
 - name: host1
   inventory: Ansible Inventory
   variables:
     ansible_connection: local
     ansible_python_interpreter: '{{ ansible_playbook_python }}'
 - name: host2
   inventory: Demo Inventory3
 - name: host3
   inventory: Demo Inventory3
