---
controller_hosts:
 - name: RedHat.example.com
   inventory: Demo Inventory2
   variables:
     ansible_connection: local
     ansible_python_interpreter: '{{ ansible_playbook_python }}'
 - name: RedHat2.example.com
   inventory: Demo Inventory3
 - name: RedHat3.example.com
   inventory: Demo Inventory3
  
...
