---
controller_hosts:
 - name: redhat.example.com
   inventory: Ansible Inventory
   variables:
     ansible_connection: local
     ansible_python_interpreter: '{{ ansible_playbook_python }}'
 - name: redhat2.example.com
   inventory: Demo Inventory2
 - name: redhat3.example.com
   inventory: Demo Inventory2
